#!/bin/bash
#modified from http://www.linuxjournal.com/article/3121

exec 0</dev/${1} 1>/dev/${1} 2>&1
shift
#pretty up the tty under it
clear

#transfer the TERM variable specified
export TERM=${1}
shift

#try to grab the right LC_CTYPE
. /etc/locale.conf
export LC_CTYPE=${LC_CTYPE:-C}

if [[ ${TERM} == "fbterm" ]];then
	img="$(cat /etc/ncdm/sys.cfg|grep ^FBIMG=|cut -d= -f2-)"
	if [ -f "$img" ];then
		exec fbterm-bi ${img} python /usr/share/ncdm/main.py $*
	else
		#add a work around in case any splash has set the background img for this terminal
		export FBTERM_BACKGROUND_IMAGE=1
		exec fbterm python /usr/share/ncdm/main.py $*
	fi
else
	exec python /usr/share/ncdm/main.py $*
fi
